from PIL import Image, ImageDraw
import os

#THIS IMAGE PROCESSOR SHOULD ONLY BE USED WITH WBPhotos generated by the Minigantry @ UCSB
#Other images may not be compatible with the code and may not work as intended.

Current_Module = "MHF1WCSB0005"  # Set the current module name

working_dir = os.getcwd()  # Get current working directory
img = Image.open(os.path.join(working_dir, "Training_Images", Current_Module, "1_13_14.png"))  # Open the image file
# "C:\Users\Admin\Documents\GitHub\Wirebond_Machine_Inspection\Training_Images\MHF1WCSB0005\1_13_14.png"
#img.show()
#pixels = img.load()  # Access pixel data
#print("This is the RGB Value of Pixel (0, 0):", pixels[0, 0])  # Print the RGB values of the pixel at (0, 0)

cropped_img = img.crop((400, 375, 1400, 1200))
cropped_img.show()  # Display the cropped image

#Next Step: Filter the Image to enhance the Visible Sicion:

cropped_img = cropped_img.convert("RGB")
d = cropped_img.getdata()

new_image_data = []

for item in d:

    r, g, b = item
    brightness = r + g + b

    # Default output is the original pixel
    out = item

    # PCB color filter
    if g < 150:
        out = (0, 0, 0)
    
    # Silkscreen filter: 60<R<140, 140<G<220, 180<B<260
    elif r > 60 and r < 140 and g > 140 and g < 220 and b > 180 and b < 260:
        out = (0, 0, 0)

    # Brightness filter
    elif brightness > 550:
        out = (0, 0, 0)

    else: out = (255, 255, 255)
    new_image_data.append(out)

# reconstruction:
new_image = Image.new("RGB", cropped_img.size)
new_image.putdata(new_image_data)

new_image.show()

def filter_image(cropped_img):
    d = cropped_img.getdata()
    new_image_data = []

    for item in d:
        r, g, b = item
        brightness = r + g + b

        # Default output
        out = item

        # PCB color filter
        if g < 150:
            out = (0, 0, 0)

        # Silkscreen filter
        elif 60 < r < 140 and 140 < g < 220 and 180 < b < 260:
            out = (0, 0, 0)

        # Brightness filter
        elif brightness > 550:
            out = (0, 0, 0)

        else:
            out = (255, 255, 255)

        new_image_data.append(out)

    new_image = Image.new("RGB", cropped_img.size)
    new_image.putdata(new_image_data)
    return new_image

def make_ring_mask(cropped_img, cx_offset=0, cy_offset=0):
    w, h = cropped_img.size
    mask_data = []

    cx = w/2 + cx_offset
    cy = h/2 + cy_offset

    for y in range(h):
        for x in range(w):
            R = ((x - cx)**2 + (y - cy)**2)**0.5

            if 725 < R*2 < 800:
                mask_data.append((255, 0, 0))
            else:
                mask_data.append((0, 0, 0))

    mask = Image.new("RGB", (w, h))
    mask.putdata(mask_data)
    return mask
    w, h = cropped_img.size
    mask_data = []

    for y in range(h):
        for x in range(w):
            R = ((x - w/2)**2 + (y - h/2)**2)**0.5

            if 725 < R*2 < 800:
                mask_data.append((255, 0, 0))
            else:
                mask_data.append((0, 0, 0))

    mask = Image.new("RGB", (w, h))
    mask.putdata(mask_data)
    return mask

def compute_center_shift(top, bottom, left, right, gain_pixels=20):
    total_h = left + right
    total_v = top + bottom

    if total_h == 0 or total_v == 0:
        return 0.0, 0.0

    # fractional imbalance in [-1, 1]
    imbal_x = (right - left) / total_h
    imbal_y = (bottom - top) / total_v

    dx = imbal_x * gain_pixels
    dy = imbal_y * gain_pixels

    return dx, dy
    dy = (bottom - top) * gain
    dx = (right - left) * gain
    return dx, dy

def and_and_measure(new_image, mask):
    w, h = new_image.size
    pixA = new_image.load()
    pixB = mask.load()

    and_pixels = []

    # Build AND image
    for y in range(h):
        for x in range(w):
            a = (pixA[x, y] == (255,255,255))
            b = (pixB[x, y] == (255,0,0))
            and_pixels.append((255,255,255) if (a and b) else (0,0,0))

    # Create AND image
    and_img = Image.new("RGB", (w, h))
    and_img.putdata(and_pixels)

    # Load AND pixels for weight measurement
    pix = and_img.load()

    # Weight measurement ONLY inside ring mask
    top = bottom = left = right = 0

    for y in range(h):
        for x in range(w):

            # Only measure weight INSIDE the ring mask
            if pixB[x, y] != (255, 0, 0):
                continue

            # Use AND image, not filtered image
            val = 1 if pix[x, y] == (255,255,255) else 0

            if y < h//2:
                top += val
            else:
                bottom += val

            if x < w//2:
                left += val
            else:
                right += val

    return and_img, top, bottom, left, right
    

def draw_center_shift_visual(cropped_img, cx_offset, cy_offset, dx, dy):
    w, h = cropped_img.size
    cx_old = w/2 + (cx_offset - dx)
    cy_old = h/2 + (cy_offset - dy)
    cx_new = w/2 + cx_offset
    cy_new = h/2 + cy_offset

    # Make a blank white canvas
    vis = Image.new("RGB", (w, h), "black")
    draw = ImageDraw.Draw(vis)

    # Draw old center (blue)
    draw.ellipse((cx_old-8, cy_old-8, cx_old+8, cy_old+8), fill="blue")

    # Draw new center (red)
    draw.ellipse((cx_new-8, cy_new-8, cx_new+8, cy_new+8), fill="red")

    # Draw arrow (thicker + arrowhead)
    draw.line((cx_old, cy_old, cx_new, cy_new), fill="yellow", width=6)

    # Arrowhead
    ah = 12  # arrowhead size
    draw.line((cx_new, cy_new,
               cx_new - ah*(dx/abs(dx) if dx!=0 else 0),
               cy_new - ah*(dy/abs(dy) if dy!=0 else 0)),
               fill="yellow", width=6)

    return vis
    w, h = cropped_img.size
    cx_old = w/2 + (cx_offset - dx)
    cy_old = h/2 + (cy_offset - dy)
    cx_new = w/2 + cx_offset
    cy_new = h/2 + cy_offset

    # Copy image so we don't overwrite original
    vis = cropped_img.copy()
    draw = ImageDraw.Draw(vis)

    # Draw old center (blue)
    draw.ellipse((cx_old-5, cy_old-5, cx_old+5, cy_old+5), fill="blue")

    # Draw new center (red)
    draw.ellipse((cx_new-5, cy_new-5, cx_new+5, cy_new+5), fill="red")

    # Draw arrow from old → new
    draw.line((cx_old, cy_old, cx_new, cy_new), fill="yellow", width=3)

    return vis

cx_offset = 0
cy_offset = 0

for loop in range(5):
    print(f"\n--- LOOP {loop+1} ---")

    # 1. Filter image
    filtered = new_image   # you already computed this earlier

    # 2. Make ring mask with updated center
    mask = make_ring_mask(cropped_img, cx_offset, cy_offset)

    # 3. AND logic
    and_img, top, bottom, left, right = and_and_measure(filtered, mask)

    print("Top:", top, "Bottom:", bottom)
    print("Left:", left, "Right:", right)

    and_img.show()

    # 4. Compute correction
    dx, dy = compute_center_shift(top, bottom, left, right)

    # 5. Update center offsets
    cx_offset += dx
    cy_offset += dy

    print(f"Center shift applied: dx={dx:.2f}, dy={dy:.2f}")
    print(f"New center offset: cx={cx_offset:.2f}, cy={cy_offset:.2f}")

w, h = and_img.size
print(f"New center = ({w/2 + cx_offset:.2f}, {h/2 + cy_offset:.2f})")
# Visualize the shift
vis = draw_center_shift_visual(cropped_img, cx_offset, cy_offset, dx, dy)
vis.show()
