from PIL import Image, ImageDraw
import os
import numpy as np
import matplotlib.pyplot as plt
from wb_config import RAW_DIR

#THIS IMAGE PROCESSOR SHOULD ONLY BE USED WITH WBPhotos generated by the Minigantry @ UCSB
#Other images may not be compatible with the code and may not work as intended.

def Main(Current_Module, Image_Name):
    """
    Loads a raw image from the Desktop PCB_Data folder,
    crops the PCB region, and returns the cropped image.
    """

    # Build full path to the raw image
    img_path = os.path.join(RAW_DIR, Current_Module, Image_Name)

    # Load the image
    try:
        img = Image.open(img_path)
        img.load()  # Force loading the image to catch any issues early
    except Exception as e:
        print(f"[SKIP] Cannot open image {img_path}: {e}")
        return None

    # Crop the image (static crop used in your original code)
    cropped_img = img.crop((400, 375, 1400, 1200))
    #cropped_img.show()
    #Next Step: Filter the Image to enhance the Visible Sicion:

    cropped_img = cropped_img.convert("RGB")
    d = cropped_img.getdata()

    new_image_data = []

    W, H = cropped_img.size

    def compute_com_from_mask(mask, W, H):
        sum_x = 0
        sum_y = 0
        count = 0

        idx = 0
        for y in range(H):
            for x in range(W):
                r, g, b = mask[idx]
                if r > 200 and g > 200 and b > 200:   # white pixel
                    sum_x += x
                    sum_y += y
                    count += 1
                idx += 1

        if count == 0:
            return None, None

        return sum_x / count, sum_y / count
    
    def is_sensor_color(r, g, b):
        return (60 <= r <= 170) and (110 <= g <= 220) and (140 <= b <= 255)







    # ---------------------------------------------------------
    # 1. CAL-DOT FILTERING + DEBUG MASK
    # ---------------------------------------------------------
    black_count = 0
    caldot_mask = []
    Hole_Type = "Default"

    for (r, g, b) in d:
        is_black = (r < 40 and g < 40 and b < 40)
        is_sensor = is_sensor_color(r, g, b)

        # COM mask includes black OR sensor
        if is_black or is_sensor:
            caldot_mask.append((255, 255, 255))
        else:
            caldot_mask.append((0, 0, 0))

        # Detection only counts black
        if is_black:
            black_count += 1

    black_count_THRESHOLD = round(47040 * 0.8)

    if black_count > black_count_THRESHOLD:
        print("Cal-dot detected — showing mask and cropped image...")

        # Build mask image
        mask_img = Image.new("RGB", (W, H))
        mask_img.putdata(caldot_mask)

        # --- Compute COM of cal-dot mask ---
        com_x, com_y = compute_com_from_mask(caldot_mask, W, H)
        if com_x is not None:
            print("Cal-dot COM:", com_x, com_y)
            draw = ImageDraw.Draw(mask_img)
            r = 8
            draw.ellipse((com_x-r, com_y-r, com_x+r, com_y+r), fill=(255,0,0))

        mask_img.show()
        cropped_img.show()
        Hole_Type = "Cal-dot"
    else:
        print("No cal-dot detected")


    # ---------------------------------------------------------
    # 2. GUARD-RING FILTERING + DEBUG MASK
    # ---------------------------------------------------------
    gold_count = 0
    guard_mask = []

    for (r, g, b) in d:
        is_gold = (210 <= r <= 255 and 225 <= g <= 260 and 175 <= b <= 220)
        is_sensor = is_sensor_color(r, g, b)

        # COM mask includes gold OR sensor
        if is_gold or is_sensor:
            guard_mask.append((255, 255, 255))
        else:
            guard_mask.append((0, 0, 0))

        # Detection only counts gold
        if is_gold:
            gold_count += 1

    GUARD_RING_THRESHOLD = round(50265 * 0.5)

    if gold_count > GUARD_RING_THRESHOLD:
        print("Guard-ring detected — showing mask and cropped image...")

        mask_img = Image.new("RGB", (W, H))
        mask_img.putdata(guard_mask)

        # --- Compute COM of guard-ring mask ---
        com_x2, com_y2 = compute_com_from_mask(guard_mask, W, H)
        if com_x2 is not None:
            print("Guard-ring COM:", com_x2, com_y2)
            draw = ImageDraw.Draw(mask_img)
            r = 8
            draw.ellipse((com_x2-r, com_y2-r, com_x2+r, com_y2+r), fill=(255,0,0))

        mask_img.show()
        cropped_img.show()
        Hole_Type = "Guard-ring"
    else:
        print("No guard-ring detected")


    # PLEASE FIXED SECTION
    if Hole_Type == "Cal-dot":
        x_offset = com_x - (W / 2)
        y_offset = com_y - (H / 2)
        return round(x_offset), round(y_offset), 0

    elif Hole_Type == "Guard-ring":
        x_offset = com_x2 - (W / 2)
        y_offset = com_y2 - (H / 2)
        return round(x_offset), round(y_offset), 1


    for item in d:

        r, g, b = item
        brightness = r + g + b

        # Default output is the original pixel
        out = item

        # PCB color filter
        if g < 150:
            out = (0, 0, 0)
        
        # Silkscreen filter: 60<R<140, 140<G<220, 180<B<260
        elif r > 60 and r < 140 and g > 140 and g < 220 and b > 180 and b < 260:
            out = (0, 0, 0)

        # Brightness filter
        elif brightness > 550:
            out = (0, 0, 0)

        else: out = (255, 255, 255)
        new_image_data.append(out)

    # reconstruction:
    new_image = Image.new("RGB", cropped_img.size)
    new_image.putdata(new_image_data)

    #new_image.show()

    
    def mask_generater(cropped_img, x_feedback, y_feedback):

        sized_mask_data = []
        width, height = cropped_img.size
        pixels = cropped_img.load()

        center_x = width/2 + round(x_feedback)
        center_y = height/2 + round(y_feedback)

        print("center_x:", center_x, "center_y:", center_y)

        for y in range(height):
            for x in range(width):
                r, g, b = pixels[x, y]
                R = ((x - center_x)**2 + (y - center_y)**2)**0.5

                if 725 < R*2 < 800:
                    sized_mask_data.append((255, 0, 0))
                else:
                    sized_mask_data.append((0, 0, 0))

        sized_mask = Image.new("RGB", cropped_img.size)
        sized_mask.putdata(sized_mask_data)
        return sized_mask

    def is_one(pixel):
        r, g, b = pixel
        # white = 1
        if r == 255 and g == 255 and b == 255:
            return True
        # red = 1
        if r == 255 and g == 0 and b == 0:
            return True
        return False

    def AND_mask(Black_White_Image, Mask_Image):
        w, h = Mask_Image.size
        pixA = Black_White_Image.load()
        pixB = Mask_Image.load()

        and_pixels = []

        for y in range(h):
            for x in range(w):
                a = is_one(pixA[x, y])
                b = is_one(pixB[x, y])

                if a and b:
                    and_pixels.append((255, 255, 255))   # 1 → white
                else:
                    and_pixels.append((0, 0, 0))         # 0 → black

        and_img = Image.new("RGB", (w, h))
        and_img.putdata(and_pixels)
        return and_img

    def weight_distribution(and_img):
            w, h = and_img.size
            pix = and_img.load()

            top_weight = 0
            bottom_weight = 0
            left_weight = 0
            right_weight = 0

            for y in range(h):
                for x in range(w):
                    r, g, b = pix[x, y]

                    # white or red = 1, black = 0
                    val = 1 if (r > 200 and g > 200 and b > 200) or (r > 200 and g < 80 and b < 80) else 0

                    # vertical split
                    if y < h // 2:
                        top_weight += val
                    else:
                        bottom_weight += val

                    # horizontal split
                    if x < w // 2:
                        left_weight += val
                    else:
                        right_weight += val
            return top_weight, bottom_weight, left_weight, right_weight


    # --- compute center of mass of white pixels ---
    w, h = new_image.size
    pix = new_image.load()

    sum_x = 0
    sum_y = 0
    count = 0

    for y in range(h):
        for x in range(w):
            r, g, b = pix[x, y]
            if r > 200 and g > 200 and b > 200:
                sum_x += x
                sum_y += y
                count += 1

    if count > 0:
        com_x = sum_x / count
        com_y = sum_y / count

        print("Center of Mass (RED):", com_x, com_y)

        draw = ImageDraw.Draw(new_image)
        r = 8
        draw.ellipse((com_x-r, com_y-r, com_x+r, com_y+r), fill=(255,0,0))

        #new_image.show()
    else:
        print("No white pixels found; COM undefined.")



    x_feedback = 0
    y_feedback = 0
    strength = 5000  # Adjust this value to control how much the feedback influences the mask size. Higher means less influence.
    tol = 750  # or 800 if you want to be looser
    for iteration in range(10):
        # Next Step: Apply a Ring shped Mask, use weight to increase the precision of mask. 
        #print("X feedback:", x_feedback, int(x_feedback))
        #print("Y feedback:", y_feedback, int(y_feedback))
        sized_mask = mask_generater(cropped_img, x_feedback=x_feedback, y_feedback=y_feedback)

        # AND GATE IMAGE, when image 1 is red, and image 2 is white, the output is white, otherwise black.
        and_img = AND_mask(new_image, sized_mask) 
        #and_img.show()

        # Measure weight distribution in the AND image
        weights = weight_distribution(and_img)

        #print("Top weight:", weights[0], "Bottom weight:", weights[1], "-- Difference:", weights[0] - weights[1])
        #print("Left weight:", weights[2], "Right weight:", weights[3], "-- Difference:", weights[2] - weights[3])
        #print()
        #print("Weights sum:", sum(weights))

        top_bottom = weights[0] - weights[1]
        left_right = weights[2] - weights[3]

        # ---- EARLY STOP CONDITION GOES HERE ----
        if abs(top_bottom) < tol and abs(left_right) < tol:
            #print("Converged early at iteration", iteration)
            break
        # ----------------------------------------

        # Horizontal correction (left-right)
        x_feedback += (weights[2] - weights[3]) / strength

        # Vertical correction (top-bottom)
        y_feedback += (weights[0] - weights[1]) / strength  # Positive means more weight in the left half, negative means more weight in the right half
    
    print("Final X feedback:", x_feedback, "-->", round(x_feedback))
    print("Final Y feedback:", y_feedback, "-->", round(y_feedback))   
    #and_img.show()

    width, height = cropped_img.size
    print("PCB Stepped hole caculated Center: (", width/2 + round(x_feedback), ",", height/2 + round(y_feedback), ")")

    cx = width/2 + round(x_feedback)
    cy = height/2 + round(y_feedback)
    draw = ImageDraw.Draw(new_image)

    r = 4  # radius of the dot
    draw.ellipse(
        (cx - r, cy - r, cx + r, cy + r),
        fill=(0, 255, 0)
    )

    #new_image.show()

    ##### This next section needs to find the location of the mercedes symbol,
    ##### Filtering Everything But Silicon Black will be the first step, 

    def make_white_mask(cropped_img, brightness_limit):
        d = cropped_img.getdata()
        filtered = []
        count_white = 0

        for (r, g, b) in d:
            brightness = r + g + b

            if brightness < brightness_limit:
                filtered.append((255, 255, 255))
                count_white += 1
            else:
                filtered.append((0, 0, 0))

        return filtered, count_white

    brightness_thresholds = [140, 180, 220, 260, 300]
    
    for threshold in brightness_thresholds:
        print(f"Trying brightness threshold: {threshold}")
        # --- STRICT PASS ---
        filtered_image_data, count_white = make_white_mask(cropped_img, threshold)

        if count_white == 0:
            print("No white pixels with strict threshold — retrying with loose threshold")

            # --- FALLBACK PASS ---
            filtered_image_data, count_white = make_white_mask(cropped_img, brightness_limit=200)

            if count_white == 0:
                print("No white pixels even with loose threshold — skipping image")
                return None, None, None
        
        # After white mask is created:
        filtered_new_image = Image.new("RGB", cropped_img.size)
        filtered_new_image.putdata(filtered_image_data)

        # Reset before building circled image
        filtered_image_data = []

        width, height = filtered_new_image.size
        pixels = filtered_new_image.load()

        center_x = width/2
        center_y = height/2

        sum_x = 0
        sum_y = 0
        count = 0

        print("center_x:", center_x, "center_y:", center_y)

        filtered_image_data = []

        for y in range(height):
            for x in range(width):
                r, g, b = pixels[x, y]
                R = ((x - center_x)**2 + (y - center_y)**2)**0.5

                if R < 200 and r == 255 and g == 255 and b == 255:
                    filtered_image_data.append((255, 255, 255))
                    sum_x += x
                    sum_y += y
                    count += 1
                else:
                    filtered_image_data.append((0, 0, 0))

        if count > 0:
            center_of_mass_x = sum_x / count
            center_of_mass_y = sum_y / count
            print("Center of Mass:", center_of_mass_x, center_of_mass_y)
        else:
            return None, None, None
            print("No white pixels found")

        filtered_image_data = []
        green_list = []
        blue_list = []

        for y in range(height):
            for x in range(width):
                r, g, b = pixels[x, y]
                R = ((x - center_of_mass_x)**2 + (y - center_of_mass_y)**2)**0.5

                if 45 < R < 60 and r == 255 and g == 255 and b == 255:
                    filtered_image_data.append((0, 255, 0))
                    green_list.append((x, y))
                elif 90 < R < 110 and r == 255 and g == 255 and b == 255:
                    filtered_image_data.append((0, 0, 255)) 
                    blue_list.append((x, y))
                elif r == 255 and g == 255 and b == 255:
                    filtered_image_data.append((255, 255, 255))
                else:
                    filtered_image_data.append((0, 0, 0))

        linear_Points_image = Image.new("RGB", cropped_img.size)
        linear_Points_image.putdata(filtered_image_data)

        #linear_Points_image.show()

        Rad_Green = []
        for point in green_list:
            x, y = point
            theta = np.arctan2(y - center_of_mass_y, x - center_of_mass_x)
            distance = ((x - center_of_mass_x)**2 + (y - center_of_mass_y)**2)**0.5
            Rad_Green.append((theta, distance))

        Rad_Blue = []
        for point in blue_list:
            x, y = point
            theta = np.arctan2(y - center_of_mass_y, x - center_of_mass_x)
            distance = ((x - center_of_mass_x)**2 + (y - center_of_mass_y)**2)**0.5
            Rad_Blue.append((theta, distance))  

        def sort_by_theta(points):
            list_low_pi = []
            list_mid_pi = []
            list_high_pi = []

            for theta, r in points:
                # normalize angle to [0, 2π)
                if theta < 0:
                    theta += 2*np.pi

                # Your old custom angular windows
                if 0 <= theta < np.pi*(1/3):
                    list_low_pi.append((theta, r))

                elif np.pi*(1/3) <= theta < np.pi*(2/3):
                    list_low_pi.append((theta, r))

                elif np.pi*(2/3) <= theta < np.pi:
                    list_mid_pi.append((theta, r))

                elif np.pi*(9/8) <= theta < np.pi*(4/3):
                    list_mid_pi.append((theta, r))

                elif np.pi*(4/3) <= theta < np.pi*(5/3):
                    list_high_pi.append((theta, r))

                elif np.pi*(5/3) <= theta < np.pi*(17/8):
                    list_high_pi.append((theta, r))

            return list_low_pi, list_mid_pi, list_high_pi
        low, mid, high = sort_by_theta(Rad_Blue)

        def list_avg(points):
            if len(points) == 0:
                return None, None

            sum_theta = 0
            sum_r = 0

            for theta, r in points:
                sum_theta += theta
                sum_r += r

            return sum_theta / len(points), sum_r / len(points)

        def list_to_point(points):
            if len(points) == 0:
                return None, None

            sx = 0
            sy = 0

            for theta, r in points:
                # Convert polar → Cartesian
                x = center_of_mass_x + r * np.cos(theta)
                y = center_of_mass_y + r * np.sin(theta)

                sx += x
                sy += y

            return sx / len(points), sy / len(points)

        lowTheta, lowR = list_avg(low)
        midTheta, midR = list_avg(mid) 
        highTheta, highR = list_avg(high)

        def safe_polar_to_cart(center_x, center_y, R, Theta, label, img=None):
            if R is None or Theta is None:
                print(f"[WARN] Missing {label} point group — R or Theta is None")

                return None, None

            return (
                center_x + R * np.cos(Theta),
                center_y + R * np.sin(Theta)
            )


        G1_x, G1_y = safe_polar_to_cart(center_of_mass_x, center_of_mass_y, lowR,  lowTheta,  "Green Low",  img)
        G2_x, G2_y = safe_polar_to_cart(center_of_mass_x, center_of_mass_y, midR,  midTheta,  "Green Mid",  img)
        G3_x, G3_y = safe_polar_to_cart(center_of_mass_x, center_of_mass_y, highR, highTheta, "Green High", img)

        print("Green Centroids:")
        print("G1:", G1_x, G1_y)   
        print("G2:", G2_x, G2_y)
        print("G3:", G3_x, G3_y)   


        low, mid, high = sort_by_theta(Rad_Green)
        lowTheta, lowR = list_avg(low)
        midTheta, midR = list_avg(mid) 
        highTheta, highR = list_avg(high)

        B1_x, B1_y = safe_polar_to_cart(center_of_mass_x, center_of_mass_y, lowR,  lowTheta,  "Blue Low",  img)
        B2_x, B2_y = safe_polar_to_cart(center_of_mass_x, center_of_mass_y, midR,  midTheta,  "Blue Mid",  img)
        B3_x, B3_y = safe_polar_to_cart(center_of_mass_x, center_of_mass_y, highR, highTheta, "Blue High", img)

        print("Blue Centroids:")
        print("B1:", B1_x, B1_y)
        print("B2:", B2_x, B2_y)
        print("B3:", B3_x, B3_y)

        # Build list of valid lines
        lines = []

        if None not in (G1_x, G1_y, B1_x, B1_y):
            lines.append(("L1", (G1_x, G1_y, B1_x, B1_y)))

        if None not in (G2_x, G2_y, B2_x, B2_y):
            lines.append(("L2", (G2_x, G2_y, B2_x, B2_y)))

        if None not in (G3_x, G3_y, B3_x, B3_y):
            lines.append(("L3", (G3_x, G3_y, B3_x, B3_y)))

        # Need at least two lines
        if len(lines) >= 2:
            # Use the first two valid lines
            (_, (Gx1, Gy1, Bx1, By1)) = lines[0]
            (_, (Gx2, Gy2, Bx2, By2)) = lines[1]

            # Compute slopes
            m1 = (By1 - Gy1) / (Bx1 - Gx1)
            m2 = (By2 - Gy2) / (Bx2 - Gx2)

            # Compute intercepts
            b1 = Gy1 - m1 * Gx1
            b2 = Gy2 - m2 * Gx2

            # Intersection
            X = (b2 - b1) / (m1 - m2)
            Y = m1 * X + b1

            print("Vector From COM to Calculated Center: (", X - center_of_mass_x, ",", Y - center_of_mass_y, ")")
            Vector_Magnitude = ((X - center_of_mass_x)**2 + (Y - center_of_mass_y)**2)**0.5
            print("Magnitude of Vector:", Vector_Magnitude)

            X_component = (X - center_of_mass_x)
            Y_component = (Y - center_of_mass_y)



            img = np.array(cropped_img)

            

            ys = [y for y in [G1_y, G2_y, G3_y, B1_y, B2_y, B3_y] if y is not None]

            Cenroid_Count = len(ys)   ### LOOP HERE
            if Cenroid_Count >= 6:
                print("All 6 centroids found.")
                break
            else:
                print(f"Only {Cenroid_Count} centroids found. Retrying with next brightness threshold...")

    if len(ys) == 0 or ys == [None, None, None, None, None, None]:
        print("[WARN] No valid centroids found.")
        return None, None, None

    middle = sum(ys) / len(ys)
    above_count = sum(1 for y in ys if y < middle)
    more_above = above_count > len(ys) / 2

    # Count how many are above the middle (smaller Y = higher in image coordinates)
    above_count = sum(1 for y in ys if y < middle)

    # True if more than half are above
    more_above = above_count > len(ys) / 2

    print("Middle Y:", middle)
    print("Centroids above middle:", above_count)
    print("More above than below:", more_above)

    if len(ys) < 5:
        print("[WARN] Only", len(ys), "centroid pixels found. Results may be unreliable.")
        plt.figure(figsize=(8, 8))
        #plt.imshow(img)
        plt.title("Mercedes Geometry Overlay")
        plt.axis('off')

        # --- plot centroids ---
        # --- plot centroids safely ---
        green_x = [x for x in [G1_x, G2_x, G3_x] if x is not None]
        green_y = [y for y in [G1_y, G2_y, G3_y] if y is not None]

        blue_x  = [x for x in [B1_x, B2_x, B3_x] if x is not None]
        blue_y  = [y for y in [B1_y, B2_y, B3_y] if y is not None]

        plt.scatter(green_x, green_y, color='lime', s=80, label='Green centroids')
        plt.scatter(blue_x,  blue_y,  color='cyan', s=80, label='Blue centroids')

        # --- plot COM ---
        plt.scatter([center_of_mass_x], [center_of_mass_y],
                    color='orange', s=120, marker='x', label='Rough COM')

        # --- plot intersection ---
        plt.scatter([X], [Y],
                    color='red', s=150, marker='*', label='Calculated center')

        # --- draw lines ---
        def draw_line(m, b, color):
            xs = np.array([0, img.shape[1]])
            ys = m * xs + b
            plt.plot(xs, ys, color=color, linewidth=2)

        # Draw only the lines that exist
        for name, (Gx, Gy, Bx, By) in lines:
            m = (By - Gy) / (Bx - Gx)
            b = Gy - m * Gx

            if name == "L1":
                draw_line(m, b, 'magenta')
            elif name == "L2":
                draw_line(m, b, 'yellow')
            elif name == "L3":
                draw_line(m, b, 'white')

        # --- draw vector from COM → Calculated Center ---
        plt.arrow(
            center_of_mass_x, center_of_mass_y,
            X - center_of_mass_x, Y - center_of_mass_y,
            color='red',
            width=1.0,
            head_width=10,
            head_length=15,
            length_includes_head=True
        )

        plt.legend()
        #plt.show()
        



    return (round(x_feedback)), (round(y_feedback)), more_above

#PCBX, PCBY, more_above = Main("MHF1WCSB0005", "2_3_15.png")

#print("PCB Stepped Hole Center:", PCBX, PCBY)

