from PIL import Image, ImageDraw
import os
import numpy as np
import matplotlib.pyplot as plt
from wb_config import RAW_DIR

#THIS IMAGE PROCESSOR SHOULD ONLY BE USED WITH WBPhotos generated by the Minigantry @ UCSB
#Other images may not be compatible with the code and may not work as intended.

def Main(Current_Module, Image_Name):
    """
    Loads a raw image from the Desktop PCB_Data folder,
    crops the PCB region, and returns the cropped image.
    """

    # Build full path to the raw image
    img_path = os.path.join(RAW_DIR, Current_Module, Image_Name)

    # Load the image
    try:
        img = Image.open(img_path)
        img.load()  # Force loading the image to catch any issues early
    except Exception as e:
        print(f"[SKIP] Cannot open image {img_path}: {e}")
        return None

    # Crop the image (static crop used in your original code)
    # -----------------------------------------
    # 1. INITIAL STATIC CROP + TRACK ORIGIN
    # -----------------------------------------
    crop_x0, crop_y0 = 400, 375   # <--- ADD THIS
    cropped_img = img.crop((crop_x0, crop_y0, crop_x0 + 1000, crop_y0 + 825))
    #cropped_img.show()
    #Next Step: Filter the Image to enhance the Visible Sicion:

    cropped_img = cropped_img.convert("RGB")
    d = cropped_img.getdata()

    new_image_data = []

    W, H = cropped_img.size

    # -------------------------------------------------------------
    # 1. Compute COM of sensor-color pixels in the initial crop
    # -------------------------------------------------------------

    def is_sensor_color(r, g, b):
        return (60 <= r <= 170) and (110 <= g <= 220) and (140 <= b <= 255)

    def compute_sensor_com(img):
        W, H = img.size
        pix = img.load()

        sum_x = 0
        sum_y = 0
        count = 0

        for y in range(H):
            for x in range(W):
                r, g, b = pix[x, y]
                if is_sensor_color(r, g, b):
                    sum_x += x
                    sum_y += y
                    count += 1

        if count == 0:
            return None, None

        return sum_x / count, sum_y / count

    # Compute COM on the initial crop
    com_x, com_y = compute_sensor_com(cropped_img)

    # -------------------------------------------------------------
    # 2. If COM exists and is far from center → recrop the image
    # -------------------------------------------------------------
    if com_x is not None:
        dx = com_x - (W / 2)
        dy = com_y - (H / 2)

        # Threshold: how far off-center before we recrop
        RECENTER_THRESHOLD = 40

        if abs(dx) > RECENTER_THRESHOLD or abs(dy) > RECENTER_THRESHOLD:
            print(f"[REALIGN] Sensor COM offset detected: dx={dx:.1f}, dy={dy:.1f}")

            # Compute new crop window in the original full image
            new_x1 = int(400 + dx)
            new_y1 = int(375 + dy)
            new_x2 = new_x1 + W
            new_y2 = new_y1 + H

            # Clamp to image boundaries
            new_x1 = max(0, new_x1)
            new_y1 = max(0, new_y1)
            new_x2 = min(img.width, new_x2)
            new_y2 = min(img.height, new_y2)

            # Re-crop
            cropped_img = img.crop((new_x1, new_y1, new_x2, new_y2))
            cropped_img = cropped_img.convert("RGB")
            # UPDATE CROP ORIGIN AFTER RECENTERING
            crop_x0, crop_y0 = new_x1, new_y1

            print("[REALIGN] Crop window adjusted and recropped.")
        else:
            print("[REALIGN] COM close enough — no recrop needed.")
    else:
        print("[REALIGN] No sensor-color pixels found — skipping recrop.")

    W, H = cropped_img.size
    d = cropped_img.getdata()
    new_image_data = []

    def compute_com_from_mask(mask, W, H):
        sum_x = 0
        sum_y = 0
        count = 0

        idx = 0
        for y in range(H):
            for x in range(W):
                r, g, b = mask[idx]
                if r > 200 and g > 200 and b > 200:   # white pixel
                    sum_x += x
                    sum_y += y
                    count += 1
                idx += 1

        if count == 0:
            return None, None

        return sum_x / count, sum_y / count
    

    # ---------------------------------------------------------
    # 1. CAL-DOT FILTERING + DEBUG MASK
    # ---------------------------------------------------------
    black_count = 0
    caldot_mask = []
    Hole_Type = "Default"

    for (r, g, b) in d:
        is_black = (r < 40 and g < 40 and b < 40)
        is_sensor = is_sensor_color(r, g, b)

        # COM mask includes black OR sensor
        if is_black or is_sensor:
            caldot_mask.append((255, 255, 255))
        else:
            caldot_mask.append((0, 0, 0))

        # Detection only counts black
        if is_black:
            black_count += 1

    black_count_THRESHOLD = round(47040 * 0.5)

    if black_count > black_count_THRESHOLD:
        print("Cal-dot detected — showing mask and cropped image...")

        # Build mask image
        mask_img = Image.new("RGB", (W, H))
        mask_img.putdata(caldot_mask)

        # --- Compute COM of cal-dot mask ---
        com_x, com_y = compute_com_from_mask(caldot_mask, W, H)
        if com_x is not None:
            #print("Cal-dot COM:", com_x, com_y)
            draw = ImageDraw.Draw(mask_img)
            r = 8
            draw.ellipse((com_x-r, com_y-r, com_x+r, com_y+r), fill=(255,0,0))

        #mask_img.show()
        #cropped_img.show()
        Hole_Type = "Cal-dot"
    else:
        caldot = 0 #placeholder line
        #print("No cal-dot detected")


    gx = gy = None
    sx = sy = None

    # ---------------------------------------------------------
    # 2. GUARD-RING FILTERING + DEBUG MASK
    # ---------------------------------------------------------
    gold_count = 0
    guard_mask = []
    gold_mask = []
    silicon_mask = []

    for (r, g, b) in d:

        # Your gold definition (keep or tighten as needed)
        is_gold = (190 <= r <= 255 and 205 <= g <= 255 and 155 <= b <= 230)

        # Your existing silicon detection
        is_sensor = is_sensor_color(r, g, b)

        # Build masks
        if is_gold or is_sensor:
            guard_mask.append((255, 255, 255))
        else:
            guard_mask.append((0, 0, 0))

        # Separate masks for COM calculation
        gold_mask.append((255,255,255) if is_gold else (0,0,0))
        silicon_mask.append((255,255,255) if is_sensor else (0,0,0))

        if is_gold:
            gold_count += 1


    # --- Your existing threshold ---
    GUARD_RING_THRESHOLD = round(502650 * 0.4 * 0.1)

    if gold_count > GUARD_RING_THRESHOLD:

        # Compute COM of gold and silicon
        gold_com = compute_com_from_mask(gold_mask, W, H)
        silicon_com = compute_com_from_mask(silicon_mask, W, H)

        if gold_com and silicon_com:
            gx, gy = gold_com
            sx, sy = silicon_com

            # Distance between COMs
            dist = ((gx - sx)**2 + (gy - sy)**2)**0.5
            print("Gold–Silicon COM distance:", dist)

            if 180 <= dist <= 320:
                print("Guard-ring confirmed by COM distance")

                mask_img = Image.new("RGB", (W, H))
                mask_img.putdata(guard_mask)
                draw = ImageDraw.Draw(mask_img)
                r = 8

                # Draw COM dots
                draw.ellipse((gx-r, gy-r, gx+r, gy+r), fill=(0,0,255))   # gold COM (blue)
                draw.ellipse((sx-r, sy-r, sx+r, sy+r), fill=(255,0,0))   # silicon COM (red)

                # 🔵 Draw the blue line between COMs
                draw.line((gx, gy, sx, sy), fill=(0, 0, 255), width=3)

                #mask_img.show()
                #cropped_img.show()

                Hole_Type = "Guard-ring"

            else:
                print("COM distance out of range — rejecting")
                Hole_Type = "Default"

        else:
            print("Could not compute COMs — rejecting")
            Hole_Type = "None"

    else:
        print(gold_count, "gold pixels detected must be above threshold of", GUARD_RING_THRESHOLD)
        print("No guard-ring detected")
        guard = 1  # placeholder


    # PLEASE FIXED SECTION
    if Hole_Type == "Cal-dot":
        # Use silicon COM (com_x, com_y)
        X_global = crop_x0 + com_x
        Y_global = crop_y0 + com_y
        return round(X_global), round(Y_global), 0, Hole_Type

    elif Hole_Type == "Guard-ring":
        # Use gold COM (gx, gy)
        X_global = crop_x0 + gx
        Y_global = crop_y0 + gy
        return round(X_global), round(Y_global), 1, Hole_Type
         

    for item in d:

        r, g, b = item
        brightness = r + g + b

        # Default output is the original pixel
        out = item

        # PCB color filter
        if g < 150:
            out = (0, 0, 0)
        
        # Silkscreen filter: 60<R<140, 140<G<220, 180<B<260
        elif r > 60 and r < 140 and g > 140 and g < 220 and b > 180 and b < 260:
            out = (0, 0, 0)

        # Brightness filter
        elif brightness > 550:
            out = (0, 0, 0)

        else: out = (255, 255, 255)
        new_image_data.append(out)

    # reconstruction:
    new_image = Image.new("RGB", cropped_img.size)
    new_image.putdata(new_image_data)

    #new_image.show()

    
    def mask_generater(cropped_img, x_feedback, y_feedback):

        sized_mask_data = []
        width, height = cropped_img.size
        pixels = cropped_img.load()

        center_x = width/2 + round(x_feedback)
        center_y = height/2 + round(y_feedback)

        #print("center_x:", center_x, "center_y:", center_y)

        for y in range(height):
            for x in range(width):
                r, g, b = pixels[x, y]
                R = ((x - center_x)**2 + (y - center_y)**2)**0.5

                if 725 < R*2 < 800:
                    sized_mask_data.append((255, 0, 0))
                else:
                    sized_mask_data.append((0, 0, 0))

        sized_mask = Image.new("RGB", cropped_img.size)
        sized_mask.putdata(sized_mask_data)
        return sized_mask

    def is_one(pixel):
        r, g, b = pixel
        # white = 1
        if r == 255 and g == 255 and b == 255:
            return True
        # red = 1
        if r == 255 and g == 0 and b == 0:
            return True
        return False

    def AND_mask(Black_White_Image, Mask_Image):
        w, h = Mask_Image.size
        pixA = Black_White_Image.load()
        pixB = Mask_Image.load()

        and_pixels = []

        for y in range(h):
            for x in range(w):
                a = is_one(pixA[x, y])
                b = is_one(pixB[x, y])

                if a and b:
                    and_pixels.append((255, 255, 255))   # 1 → white
                else:
                    and_pixels.append((0, 0, 0))         # 0 → black

        and_img = Image.new("RGB", (w, h))
        and_img.putdata(and_pixels)
        return and_img

    def weight_distribution(and_img):
            w, h = and_img.size
            pix = and_img.load()

            top_weight = 0
            bottom_weight = 0
            left_weight = 0
            right_weight = 0

            for y in range(h):
                for x in range(w):
                    r, g, b = pix[x, y]

                    # white or red = 1, black = 0
                    val = 1 if (r > 200 and g > 200 and b > 200) or (r > 200 and g < 80 and b < 80) else 0

                    # vertical split
                    if y < h // 2:
                        top_weight += val
                    else:
                        bottom_weight += val

                    # horizontal split
                    if x < w // 2:
                        left_weight += val
                    else:
                        right_weight += val
            return top_weight, bottom_weight, left_weight, right_weight


    # --- compute center of mass of white pixels ---
    w, h = new_image.size
    pix = new_image.load()

    sum_x = 0
    sum_y = 0
    count = 0

    for y in range(h):
        for x in range(w):
            r, g, b = pix[x, y]
            if r > 200 and g > 200 and b > 200:
                sum_x += x
                sum_y += y
                count += 1

    if count > 0:
        com_x = sum_x / count
        com_y = sum_y / count

        #print("Center of Mass (RED):", com_x, com_y)

        draw = ImageDraw.Draw(new_image)
        r = 8
        draw.ellipse((com_x-r, com_y-r, com_x+r, com_y+r), fill=(255,0,0))

        #new_image.show()



    x_feedback = 0
    y_feedback = 0
    strength = 5000  # Adjust this value to control how much the feedback influences the mask size. Higher means less influence.
    tol = 750  # or 800 if you want to be looser
    for iteration in range(10):
        # Next Step: Apply a Ring shped Mask, use weight to increase the precision of mask. 
        #print("X feedback:", x_feedback, int(x_feedback))
        #print("Y feedback:", y_feedback, int(y_feedback))
        sized_mask = mask_generater(cropped_img, x_feedback=x_feedback, y_feedback=y_feedback)

        # AND GATE IMAGE, when image 1 is red, and image 2 is white, the output is white, otherwise black.
        and_img = AND_mask(new_image, sized_mask) 
        #and_img.show()

        # Measure weight distribution in the AND image
        weights = weight_distribution(and_img)

        #print("Top weight:", weights[0], "Bottom weight:", weights[1], "-- Difference:", weights[0] - weights[1])
        #print("Left weight:", weights[2], "Right weight:", weights[3], "-- Difference:", weights[2] - weights[3])
        #print()
        #print("Weights sum:", sum(weights))

        top_bottom = weights[0] - weights[1]
        left_right = weights[2] - weights[3]

        # ---- EARLY STOP CONDITION GOES HERE ----
        if abs(top_bottom) < tol and abs(left_right) < tol:
            #print("Converged early at iteration", iteration)
            break
        # ----------------------------------------

        # Horizontal correction (left-right)
        x_feedback += (weights[2] - weights[3]) / strength

        # Vertical correction (top-bottom)
        y_feedback += (weights[0] - weights[1]) / strength  # Positive means more weight in the left half, negative means more weight in the right half
    
    #print("Final X feedback:", x_feedback, "-->", round(x_feedback))
    #print("Final Y feedback:", y_feedback, "-->", round(y_feedback))   
    #and_img.show()

    width, height = cropped_img.size
    #print("PCB Stepped hole caculated Center: (", width/2 + round(x_feedback), ",", height/2 + round(y_feedback), ")")

    cx = width/2 + round(x_feedback)
    cy = height/2 + round(y_feedback)
    draw = ImageDraw.Draw(new_image)

    r = 4  # radius of the dot
    draw.ellipse(
        (cx - r, cy - r, cx + r, cy + r),
        fill=(0, 255, 0)
    )

    #new_image.show()

    ##### This next section needs to find the location of the mercedes symbol,
    ##### Filtering Everything But Silicon Black will be the first step, 

    def make_white_mask(cropped_img, brightness_limit):
        d = cropped_img.getdata()
        filtered = []
        count_white = 0

        for (r, g, b) in d:
            brightness = r + g + b

            if brightness < brightness_limit:
                filtered.append((255, 255, 255))
                count_white += 1
            else:
                filtered.append((0, 0, 0))

        return filtered, count_white

    brightness_thresholds = [140, 180, 220, 260, 300, 350]
    ys = []   # <--- ADD THIS BEFORE THE LOOP
    
    for threshold in brightness_thresholds:
        #print(f"Trying brightness threshold: {threshold}")
        # --- STRICT PASS ---
        filtered_image_data, count_white = make_white_mask(cropped_img, threshold)

        if count_white == 0:
            print("No white pixels with strict threshold — retrying with loose threshold")

            # --- FALLBACK PASS ---
            filtered_image_data, count_white = make_white_mask(cropped_img, brightness_limit=200)

            if count_white == 0:
                print("No white pixels even with loose threshold — skipping image")
                return 0, 0, 0, Hole_Type
        
        # After white mask is created:
        filtered_new_image = Image.new("RGB", cropped_img.size)
        filtered_new_image.putdata(filtered_image_data)

        # Reset before building circled image
        filtered_image_data = []

        width, height = filtered_new_image.size
        pixels = filtered_new_image.load()

        center_x = width/2
        center_y = height/2

        sum_x = 0
        sum_y = 0
        count = 0

        #print("center_x:", center_x, "center_y:", center_y)

        filtered_image_data = []

        # ---------------------------------------------------------
        # 1. STRICT COM (True center of hole)
        # ---------------------------------------------------------

        strict_sum_x = 0
        strict_sum_y = 0
        strict_count = 0

        strict_mask = []

        for y in range(height):
            for x in range(width):
                r, g, b = pixels[x, y]

                # STRICT: only pure white pixels
                if r > 230 and g > 230 and b > 230:
                    strict_mask.append((255, 255, 255))
                    strict_sum_x += x
                    strict_sum_y += y
                    strict_count += 1
                else:
                    strict_mask.append((0, 0, 0))

        # Compute strict COM
        if strict_count > 0:
            com_strict_x = strict_sum_x / strict_count
            com_strict_y = strict_sum_y / strict_count
        else:
            return 0, 0, 0, Hole_Type
        
        # ---------------------------------------------------------
        # BLACK COM (center of dark region)
        # ---------------------------------------------------------

        black_sum_x = 0
        black_sum_y = 0
        black_count = 0

        for y in range(height):
            for x in range(width):
                r, g, b = pixels[x, y]

                # black pixel = NOT white pixel
                if not (r > 230 and g > 230 and b > 230):
                    black_sum_x += x
                    black_sum_y += y
                    black_count += 1

        if black_count > 0:
            black_x_com = black_sum_x / black_count
            black_y_com = black_sum_y / black_count
        else:
            # fallback to image center if somehow everything is white
            black_x_com = center_x
            black_y_com = center_y

        # Image center
        center_x = width / 2
        center_y = height / 2

        # Distance between COM and image center
        dx = com_strict_x - center_x
        dy = com_strict_y - center_y
        dist = (dx*dx + dy*dy) ** 0.5

        # Tolerance (choose one)
        pixel_tolerance = min(width, height) * 0.10   # 10% of image size
        # pixel_tolerance = 50                        # or a fixed pixel threshold

        # If COM is too far away, fall back
        print("dist:", dist, "tolerance:", pixel_tolerance)
        if dist > pixel_tolerance:
            com_strict_x = center_x
            com_strict_y = center_y

        # ---------------------------------------------------------
        # 2. LOOSE COM (Mercedes spokes)
        # ---------------------------------------------------------

        loose_sum_x = 0
        loose_sum_y = 0
        loose_count = 0

        loose_mask = []

        for y in range(height):
            for x in range(width):
                r, g, b = pixels[x, y]

                # LOOSE: include spokes + outer ring + bright areas
                if r > 150 and g > 150 and b > 150:
                    loose_mask.append((255, 255, 255))
                    loose_sum_x += x
                    loose_sum_y += y
                    loose_count += 1
                else:
                    loose_mask.append((0, 0, 0))

        # Compute loose COM
        if loose_count > 0:
            com_loose_x = loose_sum_x / loose_count
            com_loose_y = loose_sum_y / loose_count
        else:
            com_loose_x = com_strict_x
            com_loose_y = com_strict_y

        center_of_mass_x = com_loose_x
        center_of_mass_y = com_loose_y

        # ---------------------------------------------------------
        # FINAL CENTER = weighted strict + black COM
        # ---------------------------------------------------------

        alpha = 0   # strict COM influence
        beta  = 1   # black COM influence

        final_cx = alpha * com_strict_x + beta * black_x_com
        final_cy = alpha * com_strict_y + beta * black_y_com



        filtered_image_data = []
        green_list = []
        blue_list = []

        for y in range(height):
            for x in range(width):
                r, g, b = pixels[x, y]
                R = ((x - final_cx)**2 + (y - final_cy)**2)**0.5

                if 45 < R < 60 and r == 255 and g == 255 and b == 255:
                    filtered_image_data.append((0, 255, 0))
                    green_list.append((x, y))
                elif 90 < R < 110 and r == 255 and g == 255 and b == 255:
                    filtered_image_data.append((0, 0, 255)) 
                    blue_list.append((x, y))
                elif r == 255 and g == 255 and b == 255:
                    filtered_image_data.append((255, 255, 255))
                else:
                    filtered_image_data.append((0, 0, 0))

        linear_Points_image = Image.new("RGB", cropped_img.size)
        linear_Points_image.putdata(filtered_image_data)

        #linear_Points_image.show()

        Rad_Green = []
        for point in green_list:
            x, y = point
            theta = np.arctan2(y - final_cy, x - final_cx)
            distance = ((x - final_cx)**2 + (y - final_cy)**2)**0.5
            Rad_Green.append((theta, distance))

        Rad_Blue = []
        for point in blue_list:
            x, y = point
            theta = np.arctan2(y - final_cy, x - final_cx)
            distance = ((x - final_cx)**2 + (y - final_cy)**2)**0.5
            Rad_Blue.append((theta, distance))  

        def sort_by_theta(points):
            list_low_pi = []
            list_mid_pi = []
            list_high_pi = []

            for theta, r in points:
                # normalize angle to [0, 2π)
                if theta < 0:
                    theta += 2*np.pi

                # Your old custom angular windows
                if 0 <= theta < np.pi*(1/3):
                    list_low_pi.append((theta, r))

                elif np.pi*(1/3) <= theta < np.pi*(2/3):
                    list_low_pi.append((theta, r))

                elif np.pi*(2/3) <= theta < np.pi:
                    list_mid_pi.append((theta, r))

                elif np.pi*(9/8) <= theta < np.pi*(4/3):
                    list_mid_pi.append((theta, r))

                elif np.pi*(4/3) <= theta < np.pi*(5/3):
                    list_high_pi.append((theta, r))

                elif np.pi*(5/3) <= theta < np.pi*(17/8):
                    list_high_pi.append((theta, r))

            return list_low_pi, list_mid_pi, list_high_pi
        low, mid, high = sort_by_theta(Rad_Blue)

        def list_avg(points):
            if len(points) == 0:
                return None, None

            sum_theta = 0
            sum_r = 0

            for theta, r in points:
                sum_theta += theta
                sum_r += r

            return sum_theta / len(points), sum_r / len(points)

        def list_to_point(points):
            if len(points) == 0:
                return None, None

            sx = 0
            sy = 0

            for theta, r in points:
                # Convert polar → Cartesian
                x = center_of_mass_x + r * np.cos(theta)
                y = center_of_mass_y + r * np.sin(theta)

                sx += x
                sy += y

            return sx / len(points), sy / len(points)

        lowTheta, lowR = list_avg(low)
        midTheta, midR = list_avg(mid) 
        highTheta, highR = list_avg(high)

        def safe_polar_to_cart(center_x, center_y, R, Theta, label, img=None):
            if R is None or Theta is None:
                print(f"[WARN] Missing {label} point group — R or Theta is None")

                return None, None

            return (
                center_x + R * np.cos(Theta),
                center_y + R * np.sin(Theta)
            )


        G1_x, G1_y = safe_polar_to_cart(center_of_mass_x, center_of_mass_y, lowR,  lowTheta,  "Green Low",  img)
        G2_x, G2_y = safe_polar_to_cart(center_of_mass_x, center_of_mass_y, midR,  midTheta,  "Green Mid",  img)
        G3_x, G3_y = safe_polar_to_cart(center_of_mass_x, center_of_mass_y, highR, highTheta, "Green High", img)

        #print("Green Centroids:")
        #print("G1:", G1_x, G1_y)   
        #print("G2:", G2_x, G2_y)
        #print("G3:", G3_x, G3_y)   

        low, mid, high = sort_by_theta(Rad_Green)
        lowTheta, lowR = list_avg(low)
        midTheta, midR = list_avg(mid) 
        highTheta, highR = list_avg(high)

        B1_x, B1_y = safe_polar_to_cart(center_of_mass_x, center_of_mass_y, lowR,  lowTheta,  "Blue Low",  img)
        B2_x, B2_y = safe_polar_to_cart(center_of_mass_x, center_of_mass_y, midR,  midTheta,  "Blue Mid",  img)
        B3_x, B3_y = safe_polar_to_cart(center_of_mass_x, center_of_mass_y, highR, highTheta, "Blue High", img)

        #print("Blue Centroids:")
        #print("B1:", B1_x, B1_y)
        #print("B2:", B2_x, B2_y)
        #print("B3:", B3_x, B3_y)

               # Build list of valid lines
        lines = []

        if None not in (G1_x, G1_y, B1_x, B1_y):
            lines.append(("L1", (G1_x, G1_y, B1_x, B1_y)))

        if None not in (G2_x, G2_y, B2_x, B2_y):
            lines.append(("L2", (G2_x, G2_y, B2_x, B2_y)))

        if None not in (G3_x, G3_y, B3_x, B3_y):
            lines.append(("L3", (G3_x, G3_y, B3_x, B3_y)))

        # -----------------------------------------
        # 1. Compute angles for each line
        # -----------------------------------------
        line_angles = {}   # name → angle

        for name, (Gx, Gy, Bx, By) in lines:
            dx = Bx - Gx
            dy = By - Gy
            angle = np.degrees(np.arctan2(dy, dx)) % 360
            line_angles[name] = angle

        # Only apply spacing check if we have 3 lines
        if len(lines) == 3:
            # -----------------------------------------
            # 2. Check 120° spacing
            # -----------------------------------------
            angles_sorted = sorted(line_angles.items(), key=lambda x: x[1])
            vals_sorted  = [a for _, a in angles_sorted]

            d1 = vals_sorted[1] - vals_sorted[0]
            d2 = vals_sorted[2] - vals_sorted[1]
            d3 = (vals_sorted[0] + 360) - vals_sorted[2]

            diffs = [d1, d2, d3]
            TOL = 8  # degrees tolerance

            valid_pattern = all(abs(d - 120) < TOL for d in diffs)

            # -----------------------------------------
            # 3. If invalid, remove the worst line
            # -----------------------------------------
            if not valid_pattern:
                errors = {}
                for name, angle in line_angles.items():
                    ideal_diffs = [
                        abs((angle - 0)   % 360),
                        abs((angle - 120) % 360),
                        abs((angle - 240) % 360)
                    ]
                    errors[name] = min(ideal_diffs)

                bad_line = max(errors, key=errors.get)
                print(f"[FILTER] Removing bad line: {bad_line}")
                lines = [item for item in lines if item[0] != bad_line]

        # Need at least two lines
        if len(lines) >= 2:
            # Use the first two valid lines
            (_, (Gx1, Gy1, Bx1, By1)) = lines[0]
            (_, (Gx2, Gy2, Bx2, By2)) = lines[1]

            # Helper to get (m, b) or vertical form
            def line_to_mb(x1, y1, x2, y2):
                dx = x2 - x1
                dy = y2 - y1
                if dx == 0:
                    return None, x1  # vertical: x = b
                m = dy / dx
                b = y1 - m * x1
                return m, b

            m1, b1 = line_to_mb(Gx1, Gy1, Bx1, By1)
            m2, b2 = line_to_mb(Gx2, Gy2, Bx2, By2)

            # Compute intersection robustly
            if m1 is None and m2 is None:
                # Both vertical → no intersection
                print("[WARN] Both lines vertical; cannot compute intersection.")
                X, Y = center_of_mass_x, center_of_mass_y

            elif m1 is None:
                # Line 1 vertical: x = b1
                X = b1
                Y = m2 * X + b2

            elif m2 is None:
                # Line 2 vertical: x = b2
                X = b2
                Y = m1 * X + b1

            else:
                # Non-vertical lines
                if abs(m1 - m2) < 1e-6:
                    print("[WARN] Lines nearly parallel; using COM as fallback.")
                    X, Y = center_of_mass_x, center_of_mass_y
                else:
                    X = (b2 - b1) / (m1 - m2)
                    Y = m1 * X + b1

            X_component = (X - center_of_mass_x)
            Y_component = (Y - center_of_mass_y)

            img = np.array(cropped_img)

            ys = [y for y in [G1_y, G2_y, G3_y, B1_y, B2_y, B3_y] if y is not None]

            Cenroid_Count = len(ys)
            if Cenroid_Count >= 6:
                print("All 6 centroids found.")
                break
            else:
                print(f"Only {Cenroid_Count} centroids found. Retrying with next brightness threshold...")

    if len(ys) == 0 or ys == [None, None, None, None, None, None]:
        print("[WARN] No valid centroids found.")
        return 0, 0, 0, Hole_Type

    middle = sum(ys) / len(ys)
    above_count = sum(1 for y in ys if y < middle)
    more_above = above_count > len(ys) / 2


    # True if more than half are above
    more_above = above_count > len(ys) / 2

    #print("Middle Y:", middle)
    #print("Centroids above middle:", above_count)
    print("More above than below:", more_above)

   

    if len(ys) < 5:
        print("[WARN] Only", len(ys), "centroid pixels found. Results may be unreliable.")
        #plt.figure(figsize=(8, 8))
        #plt.imshow(img)
        #plt.title("Mercedes Geometry Overlay")
        #plt.axis('off')

        # --- plot centroids ---
        # --- plot centroids safely ---
        green_x = [x for x in [G1_x, G2_x, G3_x] if x is not None]
        green_y = [y for y in [G1_y, G2_y, G3_y] if y is not None]

        blue_x  = [x for x in [B1_x, B2_x, B3_x] if x is not None]
        blue_y  = [y for y in [B1_y, B2_y, B3_y] if y is not None]

        #plt.scatter(green_x, green_y, color='lime', s=80, label='Green centroids')
        #plt.scatter(blue_x,  blue_y,  color='cyan', s=80, label='Blue centroids')

        # --- plot COM ---
        #plt.scatter([center_of_mass_x], [center_of_mass_y], color='orange', s=120, marker='x', label='Rough COM')

        # --- plot intersection ---
        #plt.scatter([X], [Y],
        #            color='red', s=150, marker='*', label='Calculated center')

        # --- draw lines ---
        def draw_line(m, b, color):
            xs = np.array([0, img.shape[1]])
            ys = m * xs + b
            plt.plot(xs, ys, color=color, linewidth=2)

        # Draw only the lines that exist
        

        # --- draw vector from COM → Calculated Center ---
        """plt.arrow(
            center_of_mass_x, center_of_mass_y,
            X - center_of_mass_x, Y - center_of_mass_y,
            color='red',
            width=1.0,
            head_width=10,
            head_length=15,
            length_includes_head=True
        )"""

        #plt.legend()
        #plt.show()

    #import matplotlib.pyplot as plt

    #plt.figure(figsize=(6,6))
    #plt.imshow(img)

    # Red dot (COM) — already in crop coordinates
    #plt.scatter([com_x], [com_y], c='red', s=80, label='COM Algorithm')

    # Blue dot (feedback) — convert from center-offset coordinates
    x_fb_plot = (W / 2) + x_feedback
    y_fb_plot = (H / 2) + y_feedback

    #plt.scatter([x_fb_plot], [y_fb_plot], c='cyan', s=80, label='Feedback Algorithm')
    
    # Green dot — geometric centroid (intersection of lines)
    #plt.scatter([X], [Y], c='lime', s=80, label='Geometric Centroid Algorithm')

    X_global = crop_x0 + X
    Y_global = crop_y0 + Y



        # --- draw the lines used for the geometric centroid ---
    def draw_line_on_final(m, b, color):
        height, width = img.shape[:2]
        xs = np.array([0, width])
        ys = m * xs + b
        plt.plot(xs, ys, color=color, linewidth=2, alpha=0.7)

    for name, (Gx, Gy, Bx, By) in lines:
        m = (By - Gy) / (Bx - Gx)
        b = Gy - m * Gx

        if name == "L1":
            draw_line_on_final(m, b, 'magenta')
        elif name == "L2":
            draw_line_on_final(m, b, 'yellow')
        elif name == "L3":
            draw_line_on_final(m, b, 'white')

    #plt.legend()
    #plt.axis('off')
    #plt.show()
        

    #print("Offset outputs:", X_component, Y_component, "vs", round(x_feedback), round(y_feedback))
    return round(X_global), round(Y_global), more_above, Hole_Type
    #return (round(x_feedback)), (round(y_feedback)), more_above, Hole_Type

#PCBX, PCBY, more_above = Main("MHF1WCSB0005", "2_3_15.png")

#print("PCB Stepped Hole Center:", PCBX, PCBY)

