from PIL import Image
import os

#THIS IMAGE PROCESSOR SHOULD ONLY BE USED WITH WBPhotos generated by the Minigantry @ UCSB
#Other images may not be compatible with the code and may not work as intended.

Current_Module = "MHF1WCSB0005"  # Set the current module name

working_dir = os.getcwd()  # Get current working directory
img = Image.open(os.path.join(working_dir, "Training_Images", Current_Module, "1_13_14.png"))  # Open the image file
# "C:\Users\Admin\Documents\GitHub\Wirebond_Machine_Inspection\Training_Images\MHF1WCSB0005\1_13_14.png"
#img.show()
#pixels = img.load()  # Access pixel data
#print("This is the RGB Value of Pixel (0, 0):", pixels[0, 0])  # Print the RGB values of the pixel at (0, 0)

cropped_img = img.crop((400, 375, 1400, 1200))
cropped_img.show()  # Display the cropped image

#Next Step: Filter the Image to enhance the Visible Sicion:

cropped_img = cropped_img.convert("RGB")
d = cropped_img.getdata()

new_image_data = []

for item in d:

    r, g, b = item
    brightness = r + g + b

    # Default output is the original pixel
    out = item

    # PCB color filter
    if g < 150:
        out = (0, 0, 0)
    
    # Silkscreen filter: 60<R<140, 140<G<220, 180<B<260
    elif r > 60 and r < 140 and g > 140 and g < 220 and b > 180 and b < 260:
        out = (0, 0, 0)

    # Brightness filter
    elif brightness > 550:
        out = (0, 0, 0)

    else: out = (255, 255, 255)
    new_image_data.append(out)

# reconstruction:
new_image = Image.new("RGB", cropped_img.size)
new_image.putdata(new_image_data)

new_image.show()

# Next Step: Apply a Ring shped Mask, use weight to increase the precision of mask. 
sized_mask_data = []

width, height = cropped_img.size
pixels = cropped_img.load()

for y in range(height):
    for x in range(width):
        r, g, b = pixels[x, y]
        R = ((x - width/2)**2 + (y - height/2)**2)**0.5  # Calculate distance from center

        # Now you have BOTH:
        # - pixel value (r, g, b)
        # - pixel location (x, y)

        # Example: turn top-left 100×100 region black
        if R*2 > 725 and R*2 < 800:      #R*2 is diameter, 725 and 880 are the inner and outer diameter of the ring mask, respectively.
            sized_mask_data.append((255, 0, 0))
        else:
            sized_mask_data.append((0, 0, 0))

sized_mask = Image.new("RGB", cropped_img.size)
sized_mask.putdata(sized_mask_data)
sized_mask.show()

#merge images as a visualization tool to see the effectiveness of the mask: 
overlay = Image.blend(cropped_img, sized_mask, alpha=0.5)
overlay.show()


# AND GATE IMAGE, when image 1 is red, and image 2 is white, the output is white, otherwise black.
def is_one(pixel):
    r, g, b = pixel
    # white = 1
    if r == 255 and g == 255 and b == 255:
        return True
    # red = 1
    if r == 255 and g == 0 and b == 0:
        return True
    return False

w, h = cropped_img.size
pixA = new_image.load()
pixB = sized_mask.load()

and_pixels = []

for y in range(h):
    for x in range(w):
        a = is_one(pixA[x, y])
        b = is_one(pixB[x, y])

        if a and b:
            and_pixels.append((255, 255, 255))   # 1 → white
        else:
            and_pixels.append((0, 0, 0))         # 0 → black

and_img = Image.new("RGB", (w, h))
and_img.putdata(and_pixels)
#Showing the AND gate output image
and_img.show()

# Measure weight distribution in the AND image
w, h = and_img.size
pix = and_img.load()

top_weight = 0
bottom_weight = 0
left_weight = 0
right_weight = 0

for y in range(h):
    for x in range(w):
        r, g, b = pix[x, y]

        # white or red = 1, black = 0
        val = 1 if (r > 200 and g > 200 and b > 200) or (r > 200 and g < 80 and b < 80) else 0

        # vertical split
        if y < h // 2:
            top_weight += val
        else:
            bottom_weight += val

        # horizontal split
        if x < w // 2:
            left_weight += val
        else:
            right_weight += val

print("Top weight:", top_weight)
print("Bottom weight:", bottom_weight)
print("Left weight:", left_weight)
print("Right weight:", right_weight)
